stages:
  create_dataset:
    cmd: python studentpredictor/create_dataset.py
    deps:
    - studentpredictor/create_dataset.py
    outs:
    - assets/data
  feature:
    cmd: python studentpredictor/create_features.py
    deps:
    - assets/data
    - studentpredictor/create_features.py
    outs:
    - assets/features
